apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "db4fresh.fullname" . }}-config
  labels:
    {{- include "db4fresh.labels" . | nindent 4 }}
data:
  PORT: "4000"
  DB_HOST: {{ .Values.env.DB_HOST | default "localhost" | quote }}
  DB_USER: {{ .Values.env.DB_USER | default "db_user" | quote }}
  DB_NAME: {{ .Values.env.DB_NAME | default "db4fresh" | quote }}
  KAFKA_BROKER: {{ .Values.env.KAFKA_BROKER | default "kafka:9092" | quote }}
  NODE_ENV: {{ .Values.env.NODE_ENV | default "production" | quote }}
