apiVersion: v1
kind: Service
metadata:
  name: {{ include "db4fresh.fullname" . }}-backend
  labels:
    {{- include "db4fresh.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "db4fresh.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
