apiVersion: v1
kind: Service
metadata:
  name: {{ include "db4fresh.fullname" . }}-frontend
  labels:
    {{- include "db4fresh.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  {{- with .Values.service.frontend.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "db4fresh.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
